version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: hrms-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrms
    volumes:
      - hrms_pg_data:/var/lib/postgresql/data
volumes:
  hrms_pg_data:
